### ISSUE TITLE
Uncaught TypeError: images.map is not a function

### ISSUE THREAD

**Issue by robdt** [jtojnar/markdown-image-insertion#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Mac OS X 10.15.7
**Thrown From**: [markdown-image-insertion](https://github.com/jtojnar/markdown-image-insertion) package 0.2.2

### Stack Trace

Uncaught TypeError: images.map is not a function

```
At /Users/rtaylo231/.atom/packages/markdown-image-insertion/lib/markdown-image-insertion.js:61

TypeError: images.map is not a function
    at Object.insertImages (/packages/markdown-image-insertion/lib/markdown-image-insertion.js:61:21)
    at HTMLElement.markdownImageInsertionInsertImages (/packages/markdown-image-insertion/lib/markdown-image-insertion.js:16:57)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350382)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348857)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:727563)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:735513)
    at EventEmitter.emit (events.js:200:13)
    at Object.onMessage (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/init.js:42:16)
```

### Commands

```
  9x -2:45.2.0 core:backspace (input.hidden-input)
     -2:03.9.0 core:paste (input.hidden-input)
 32x -1:58.9.0 core:backspace (input.hidden-input)
  2x -1:31.3.0 markdown-image-insertion:insert-images (input.hidden-input)
```

### Non-Core Packages

```
markdown-image-insertion 0.2.2 
markdown-preview-plus 4.9.0 
vim-mode-plus 1.36.4 
```

**Comment by jtojnar** [comment]
Thanks for reporting.

Looks like they changed the API of [`dialog.showOpenDialog`](https://www.electronjs.org/docs/api/dialog#dialogshowopendialogbrowserwindow-options) to return a promise.

I do not have access to Atom at the moment. Could you try if https://github.com/jtojnar/markdown-image-insertion/commit/63fecf531ee526b7d1a523197a0683606b58a604 fixes the issue?

**Comment by robdt** [comment]
Thank you for looking at this so quickly. I should be able to try that out
later tonight. Will let you know if it fixes the issue.
